### ISSUE TITLE
Doesnt extract all the loaded images from 9gag

### ISSUE THREAD

**Issue by eja-ne** [B3n3/9gag_downloader#2]
First of all, thank you for your effort to make 9gag upvotes downloadable. 

Posts which have been loaded arent extracted. It extract only recently loaded images. 

However, once 9gag is extracted, downloading is working perfectly.

**Comment by B3n3** [comment]
Hi @eja-ne , thanks for pointing out the issue.
I've reworked the code and updated the README with instructions.
You should now be able to download all your posts.

In case you face any further issues, feel free to raise a new issue.
Thanks, Ben
